knowledge_repo/app/routes/auth.py
from flask import flash, redirect, render_template, request, current_app, Blueprint, url_for
from flask_login import login_user, logout_user, login_required
from flask_principal import identity_changed, AnonymousIdentity, PermissionDenied

from ..models import User
from ..proxies import current_app
from ..utils.auth import is_safe_url

blueprint = Blueprint('auth', __name__,
                      template_folder='../templates', static_folder='../static')


@blueprint.route('/auth/login', methods=['GET', 'POST'])
def login():

    providers = current_app.auth_providers

    if len(providers) == 1:
        return redirect(url_for('auth_provider.{}.prompt'.format(providers[0].name)))

    return render_template(
        'auth-switcher.html',
        providers=[{'name': provider.name, 'icon_uri': provider.icon_uri, 'link_text': provider.link_text} for provider in providers]
    )


@blueprint.route("/auth/logout")
@login_required
def logout():
    logout_user()

    # Notify flask principal that the user has logged out
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())

    return redirect(url_for('index.render_feed'))

knowledge_repo/app/routes/stats.py
import datetime
import json
import collections
from flask import Blueprint, request, render_template
from sqlalchemy import func

from .. import permissions
from ..proxies import db_session
from ..models import PageView, Post
from ..utils.requests import from_request_get_feed_params
from ..utils.posts import get_posts

blueprint = Blueprint('stats', __name__,
                      template_folder='../templates', static_folder='../static')


def _round_date(d):
    """Round date to the previous Monday"""
    return d - datetime.timedelta(d.weekday())


@blueprint.route('/post_stats', methods=['GET'])
@PageView.logged
@permissions.post_view.require()
def post_stats():
    """ Return the total views, distinct views, total likes and total comments
        for a given post """
    post_id = request.args.get('post_id', '')
    post = (db_session.query(Post)
                      .filter(Post.path == post_id)
                      .first())
    if not post:
        return json.dumps({})
    return json.dumps({'all_views': post.view_count,
                       'distinct_views': post.view_user_count,
                       'total_likes': post.vote_count,
                       'total_comments': post.comment_count})


@blueprint.route('/stats', methods=['GET'])
@PageView.logged
@permissions.stats_view.require()
def stats():
    """ Render the stats page, creating graphs for
        pageviews daily, weekly, post creation weekly and
        cumulative posts per week
    """
    feed_params = from_request_get_feed_params(request)

    # count daily and weekly pageviews
    datetime_pageviews = (db_session.query(PageView.created_at, func.count(PageView.id))
                                    .group_by(PageView.created_at)
                                    .all())

    daily_pageviews = {}
    weekly_pageviews = {}
    for k, v in datetime_pageviews:
        d = k.date()
        wk = _round_date(d)
        daily_pageviews[d] = daily_pageviews.get(d, 0) + v
        weekly_pageviews[wk] = weekly_pageviews.get(wk, 0) + v

    # count post creation (created and updated)
    posts = (db_session.query(Post)
                       .filter(Post.is_published).all())

    created_at_counts = collections.Counter([_round_date(post.created_at.date()) for post in posts])
    updated_at_counts = collections.Counter([_round_date(post.updated_at.date()) for post in posts])

    all_week_keys = set(created_at_counts.keys()).union(updated_at_counts.keys())
    weekly_posts_created_and_updated = dict((k, [created_at_counts.get(k, 0), updated_at_counts.get(k, 0)])
                                            for k in all_week_keys)

    # cumulative weekly post created
    weekly_cumulative_posts = {}
    cum_created_val = 0
    for week in sorted(all_week_keys):
        cum_created_val += created_at_counts.get(week, 0)
        weekly_cumulative_posts[week] = cum_created_val

    # count post per author
    posts, _ = get_posts(feed_params)
    post_per_author_count = collections.Counter([author.format_name for post in posts for author in post.authors])

    return render_template('stats.html',
                           feed_params=feed_params,
                           daily_pageviews=daily_pageviews,
                           weekly_posts_created_and_updated=weekly_posts_created_and_updated,
                           weekly_cumulative_posts=weekly_cumulative_posts,
                           weekly_pageviews=weekly_pageviews,
                           post_per_author_count=post_per_author_count)

knowledge_repo/app/templates/all_groups.html
{% extends "base.html" %}

{% block title %} Knowledge {% endblock %}

{% block content %}
<div class="row col-12">
  <div class="panel">
    <div class="panel-header">
      All Groups
    </div>
    <div class="panel-body">
      <div class="col-12">
        <textarea style='width: 80%; vertical-align:middle'
                  placeholder=' Add new group names, separated by commas'
                  id='add_groups'></textarea>
        <button class="btn btn-large btn-default" style='vertical-align:bottom' id="btn_submit">Add groups</button>
      </div>
      <br> <br>
      <h4> Existing Groups </h4>
      <ul style='list-style-type:none'>
        {% for group in groups %}
        <li> <a href="/add_group_users?group_id={{group.id}}"> {{ group.name }}</a></li>
        <br>
        {% endfor %}
      <ul>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super () }}
<script>
$("#btn_submit").on("click", function(){
    groups = $('#add_groups')[0].value.split(",")
    $.ajax({
      type: "POST",
      dataType: "json",
      data: JSON.stringify(groups),
      contentType: "application/json",
      url: '/add_groups',
      async: false,
    });
    location.reload();
});
</script>
{% endblock %}

knowledge_repo/app/templates/auth-login-form.html
{% extends "auth-switcher.html" %}

{% block content %}

<style>
.login-form {
    display: block;
    list-style-type: none;
    margin: 10px;
    padding: 1em;
    background: #fff;
    border: 1px solid #aaa;
    border-radius: 5px;
    box-sizing: border-box;
}
.login-form > input {
    display: block;
    width: 100%;
    border: 1px solid #aaa;
    border-radius: 3px;
    padding: 1em;
    margin-bottom: 10px;
    -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */
    -moz-box-sizing: border-box;    /* Firefox, other Gecko */
    box-sizing: border-box;         /* Opera/IE 8+ */
}
.login-form > input[type=submit] {
    margin-bottom: 0px;
}
</style>

<form name='login' action='authorize' method='POST' class='login-form'>
<input type='text' placeholder="Username" name='username' />
{% if not skip_password %}
<input type='password' placeholder="Password" name='password' />
{% endif %}
<input type='submit' value='Sign in'/>
</form>
{% endblock %}

knowledge_repo/app/templates/auth-switcher.html
{% extends "base.html" %}

{% block title %}
Knowledge Repo Login
{% endblock %}

{% block extra_headers %}
<link rel='stylesheet' href='{{ url_for("static", filename="css/pages/auth-switcher.css") }}'>
{% endblock %}

{% block navbar %}
<!-- Top-level navbar -->
<nav class="navbar navbar-inverse" style='border-radius: 0px;'>
  <div class="container">
    <div class="navbar-header" style='float:none'>
      <!-- Brand name / logo -->
      <a class="navbar-brand" href="/" class="logo-image">
        <img src='{{ url_for("static", filename="images/logo-white.svg") }}' />
      </a>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
{% if providers %}
<span class='auth-message'>
  The content you are attempting to access requires that you are logged in.
  Please sign in using one of the following login methods to continue.
</span>
<ul class='auth-providers'>
{% for provider in providers %}
    <li><a href='login/{{ provider['name'] }}?next={{request.args.next}}'><img src='{{ provider['icon_uri'] }}' />{{ provider['link_text'] }}</a></li>
{% endfor %}
</ul>
{% else %}
<span class='auth-message'>
  The content you are attempting to access requires that you are logged in.
  <br><br>
  Unfortunately, there are no authentication mechanisms configured. Please contact your system administrator to enable authentication.
</span>
{% endif %}
{% endblock %}

knowledge_repo/app/templates/index-base.html
{% extends "base.html" %}

{% macro format_authors(authors) %}
  {% for author in authors %}
    <a href='/feed?authors={{ author.identifier|urlencode }}'>
      {{ author.format_name }}
    </a>
    {% if not loop.last %}
      ,
    {% endif %}
  {% endfor %}
{% endmacro %}

{% macro pagination(max_pages=10, extremes=True, autohide=True) %}
  {% if feed_params %}
    {% set start = feed_params['start'] | default(0) %}
    {% set results = feed_params['results'] | default(10) %}
    {% set page = 1 if (start == 0) else (start//results + 1) %}
    {% set page_count = feed_params['page_count'] | default(1) %}

    {% if autohide and page_count > 1 %}
      {% set page_nums = pagination_pages(current_page=page, page_count=page_count, max_pages=max_pages, extremes=extremes) %}
      <div class='pagination-bar' role="group">
        <a href="{{ "#" if (page == 1) else modify_query(start=(page-2)*results) }}" class="pagination-stepper{% if page == 1 %} disabled{% endif %}"{% if page == 1 %} onclick="return false;"{% endif %}>
          <i class="glyphicon glyphicon-chevron-left"></i>
        </a>
        <ul class="pagination">
          {% for page_num in page_nums %}
            {% if loop.index0 > 0 and page_num - page_nums[loop.index0 - 1] > 1 %}
              <li class="disabled"><a>&middot;&middot;&middot;</a></li>
            {% endif %}
            <li {% if page == page_num %}class="active"{% endif %}><a href= "{{ modify_query(start=(page_num-1)*results) }}"> {{ page_num }} </a></li>
          {% endfor %}
        </ul>
        <a href="{{ "#" if (page == page_count) else modify_query(start=page*results) }}" class="pagination-stepper{% if page == page_count %} disabled{% endif %}"{% if page == page_count %} onclick="return false;"{% endif %}>
          <i class="glyphicon glyphicon-chevron-right"></i>
        </a>
      </div>

    {% endif %}
  {% endif %}
{% endmacro %}

{% block content %}
  <!-- Index rendering mode switch -->
  <div class="row">
    <div class="col-md-5">
      <div class="btn-group btn-group-justified index-view-btn-group" role="group">
        <a href="/feed" class="btn btn-default btn-card no-underline" role="button">
          <i class="glyphicon glyphicon-post-org glyphicon-align-justify"></i>
          <span class="index-view-name"> Card </span>
        </a>
        <a href="/table" class="btn btn-default btn-table no-underline" role="button">
          <i class="glyphicon glyphicon-post-org glyphicon-th"></i>
          <span class="index-view-name"> Table </span>
        </a>
        <a href="/cluster" class="btn btn-default btn-cluster no-underline" role="button">
          <i class="glyphicon glyphicon-post-org glyphicon-th-list"></i>
          <span class="index-view-nane"> Cluster </span>
        </a>
      </div>
    </div>

    {# Show pagination at top unless showing clusters. #}
    {% if request.endpoint != 'index.render_cluster' %}
    <div class='pull-right visible-md-block visible-lg-block'>
      {{ pagination(max_pages=5, extremes=False) }}
    </div>
    {% endif %}

  </div>

  <!-- Container for index items -->
  <div class="col-12">
    {% block inner_content %}
    {% endblock %}
  </div>

  {# Show pagination at bottom of page unless showing clusters. #}
  {% if request.endpoint != 'index.render_cluster' %}
  {{ pagination(max_pages=10) }}
  {% endif %}

{% endblock %}

knowledge_repo/app/templates/permission_denied.html
{% extends "base.html" %}

{% block title %}
Knowledge Repo 403
{% endblock %}

{% block content %}
<div class="col-12">
  <div class="panel">
    <center>
        <div class="panel-header">
          Error!
        </div>
    </center>

    <center>
        <div class="panel-body">
          <div class="row row-space-2"></div>
          <h3> You don't have permission to view this page! </h3>
          {% if current_user.is_authenticated %}
          <text> If you think you should have access to this page, please contact a site admin. </text>
          {% else %}
          <text> <a href="{{ url_for('auth.login') }}">Click here</a> to sign in, and then try accessing this page again. </text>
          {% endif %}
        </div>
    </center>
  </div>
</div>
{% endblock %}

knowledge_repo/app/templates/post_editor_markdown.html
{% extends "post_editor_base.html" %}

{% block render_block %}
<hr class="row col-md-12" style="border-top:1px solid #9ca299; margin-left: 15px; width: 93%">
<div class="row col-md-12">
  <div class="col-md-1 group-by-header">
    <h5> View:</h5>
  </div>
  <div class="col-md-5">
    <span class="group-by-options">
    <div class="radio-inline radio-cluster">
      <label>
        <input type="radio" name="cluster-radio" id="markdown-only">Text Editor Only
      </label>
    </div>
    <div class="radio-inline radio-cluster">
      <label>
        <input type="radio" name="cluster-radio" id="split-view" checked='checked'> Split View
      </label>
    </div>
    <div class="radio-inline radio-cluster">
      <label>
        <input type="radio" name="cluster-radio" id="rendered-only">Rendered Only
      </label>
    </div>
  </span>
  </div>
</div>
<div class="row row-space-3"></div>

<div class="row">
  <div class="col-md-12">
    <a class="col-md-3" target="_blank" rel="noopener noreferrer" href="https://daringfireball.net/projects/markdown/basics" style="padding-right: 13px">
     How to write Markdown
     <i class="glyphicon glyphicon-new-window"></i>
   </a>
  </div>
</div>
<div class="row row-space-2"></div>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-6" id="post_text_div">
      <textarea class="input input-resize-both form-control" id="post_text" type="text" placeholder="Start writing markdown here" style="height:100%; width:100%">{{markdown if markdown}}
      </textarea>
    </div>
    <div class="col-md-6" id="rendered-markdown">
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}

{{ super() }}

<script>
  $("#markdown-only").on("click", function() {
    var md_text = $("#post_text_div")[0];
    var rendered_text = $("#rendered-markdown")[0];
    md_text.className = "col-md-12"
    md_text.style.visibility = "visible"
    rendered_text.style.visibility = "hidden";
    rendered_text.style.display = "none";
  })

  $("#split-view").on("click", function() {
    var md_text = $("#post_text_div")[0];
    var rendered_text = $("#rendered-markdown")[0];
    md_text.className = "col-md-6";
    md_text.style.visibility = "visible";
    md_text.style.display = "inherit";
    rendered_text.className = "col-md-6";
    rendered_text.style.visibility = "visible";
    rendered_text.style.display = "inherit";
  });

  $("#rendered-only").on("click", function() {
    var md_text = $("#post_text_div")[0];
    var rendered_text = $("#rendered-markdown")[0];
    md_text.style.visibility = "hidden";
    md_text.style.display = "none";
    rendered_text.className = "col-md-12";
    rendered_text.style.visibility = "visible";
    rendered_text.style.display = "inherit";
  })

  function refreshRenderedMarkdown() {
    var markdownString = $('#post_text').val();

    var metadata_ids = ['#post_title', '#post_author', '#post_created_at',
      '#post_updated_at', '#post_tags', '#post_tldr'
    ]
    var metadata_vals = {}
    $.each(metadata_ids, function(i, mid) {
      metadata_key = mid.split("_")[1];
      textfield = $(mid)[0].value;
      metadata_vals[metadata_key] = textfield;
    });

    // authors and tags are a little bit different
    tags = $("#post_tags").select2().val()
    if (tags !== null) {
      metadata_vals['tags'] = tags.join(", ")
    } else {
      metadata_vals['tags'] = ''
    }

    author = $("#post_author").select2().val()
    if (author !== null) {
      metadata_vals['author'] = author.join(", ")
    } else {
      metadata_vals['author'] = ''
    }

    metadata_content =
      "<h1>" + metadata_vals['title'] + "</h1>" +
      "<p><strong>Author</strong>: " + metadata_vals['author'] + "<br/>" +
      "<strong>Date Created</strong>: " + metadata_vals['created'] + "<br/>" +
      "<strong>Date Updated</strong>: " + metadata_vals['updated'] + "<br/>" +
      "<strong>Tags</strong>: " + metadata_vals['tags'] + "<br/>" +
      "<strong>TLDR</strong>: " + metadata_vals['tldr'] + "<br/> </p>"

    //escape underscores in equations
    var blocks = markdownString.split('```')
    markdownString = metadata_content
    for (var i = 0; i < blocks.length; i++) {
      if (i % 2 == 1) {
        var block = blocks[i]
        markdownString += block + '```'
      } else {
        var block = blocks[i]
        block = escapeEquationBlocks(block, '$$')
        block = escapeEquationBlocks(block, '$')
        markdownString += block
        if (i != blocks.length - 1) {
          markdownString += '```'
        }
      }
    }

    // Using async version of marked
    marked(markdownString, function(err, content) {
      if (err) throw err;
      //make sure images are not larger than the page
      content = content.split('<img ').join('<img style="max-width:100%"')
        //make tables look prettier:
      content = content.split('<table>').join('<table class="table table-striped table-condensed table-bordered">')
      content = content.split('<table class="dataframe">').join('<table class="table table-striped table-condensed table-bordered">')
      $('#rendered-markdown').html(content)
    });

    try {
      MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
    } catch (e) {
      //console.log(e);
    }
  }

  var timeout = null;
  $("#post_text").on("input", function(e) {
    if ($(this).data("lastval") != $(this).val()) {
      $(this).data("lastval", $(this).val());


      if (timeout !== null) {
        clearTimeout(timeout);
      }
      //if no new input is entered within 1 second, apply the filters
      timeout = setTimeout(function() {
        refreshRenderedMarkdown();
      }, 500);
    };
  });

  var metadata_fields = ['#post_title', '#post_author', '#post_created_at',
    '#post_updated_at', '#post_tags', '#post_tldr'
  ]

  $.each(metadata_fields, function(i, field) {
    var timeout = null;
    if (field != "#post_tags") {
      $(field).on("input", function(e) {
        if ($(this).data("lastval") != $(this).val()) {
          $(this).data("lastval", $(this).val());

          if (timeout !== null) {
            clearTimeout(timeout);
          }
          //if no new input is entered within 1 second, apply the filters
          timeout = setTimeout(function() {
            refreshRenderedMarkdown();
          }, 500);
        };
      });
    }
  })

  $(document).ready(function() {
    marked.setOptions({
      highlight: function(code, lang) {
        try {
          return hljs.highlight(lang, code, true).value;
        } catch (err) {
          console.log(err)
          try {
            return hljs.highlightAuto(code).value;
          } catch (err) {
            return code;
          }
        }
      },
      renderer: new marked.Renderer(),
      gfm: true,
      toc: true,
      tables: true,
      breaks: true,
      pedantic: false,
      sanitize: false,
      smartLists: true,
      smartypants: true
    });
    var hash = window.location.hash;
    if (hash) {
      var text = decodeURIComponent(hash)
      text = text.replace("#", '')
    }
    var text = $("#post_text").text()
    var len = text.split(/\r\n|\r|\n/).length
    $("#post_text").text(text)
    refreshRenderedMarkdown();
  });

</script>
{% endblock scripts %}

knowledge_repo/app/templates/post_editor_proxy.html
{% extends "post_editor_base.html" %}

{% block metadata_fields %}
{{ super() }}
<label for="post_proxy"> Proxy URL: </label>
<input id="post_proxy"
       class="form-control"
       type="text"
       value="{{ proxy if proxy else ''}}"></input>
<br>
{% endblock %}


{% block render_block %}
<a href="{{ proxy }}">Linked Post</a>
<iframe width=100% height=800 src="{{ proxy }}"></iframe>'
{% endblock render_block %}

knowledge_repo/app/templates/post_editor_review_modal.html
<div class="modal"
  id="webpost-send-for-review-modal"
  role="dialog"
  aria-hidden="true"
  aria-labelledby="modal-body-label"
  aria-describedby="modal-body">
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">
            Who should review this post?
          </h4>
        </div>

        <div class="modal-body">
          Comma-separate the emails, and the reviewers will get a post saying your post is ready to review!
          <br><br>
          <form style="padding-left:12px">
            <text class="text-left" for="form-vert-text">
            Emails of the Reviewers:
            </text>
          <input id="post_reviewers" type="text" value="...@emailext.com"
                style="width:75%; display:inline-block">
        </form>
        <p>
        <button class="btn btn-primary btn-email-reviewers"
                data-behavior='modal-close'
                id='submission_close'>
          Email Reviewers!
        </button>
        </p>
      </div>
      </div>
  </div>
</div>

knowledge_repo/app/templates/stats.html
{% extends "base.html" %}


{% block title %}Stats{% endblock %}

{% block content %}

  <br>
    <div class="panel">
      <div class="panel-header">Post Activity Per Week</div>
      <div id="posts_week"></div>
    </div>
    <div class="panel">
      <div class="panel-header">Cumulative Number of Posts in the Repo</div>
      <div id="posts_cum"></div>
    </div>
    <div class="panel">
      <div class="panel-header">Pageviews per Week</div>
      <div id="pageviews_weeks"></div>
    </div>
    <div class="panel">
      <div class="panel-header">Pageviews per Day</div>
      <div id="pageviews_daily"></div>
    </div>
    <div class="panel">
      <div class="panel-header">Number of posts per author</div>
      <div id="posts_per_author"></div>
    </div>
  </br>




{% endblock %}

{% block scripts %}
{{ super () }}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load('visualization', '1', {'packages':['corechart']});
google.setOnLoadCallback(drawChart);

function drawChart() {

  var height = 500;
  var hAxisOpts = {format: 'y-MM-dd', slantedText:true, slantedTextAngle: 40, title:'Date'}

  // Daily PageViews
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Day');
  data.addColumn('number', 'Pageviews');
  data.addRows([
          {%- for k, v in daily_pageviews.items() %}
          [new Date({{ k.year }}, {{ k.month }}, {{ k.day }}), {{ v }}],
          {%- endfor %}
  ]);
  data.sort(0);
  var chart = new google.visualization.LineChart(document.getElementById('pageviews_daily'));
  chart.draw(data, {vAxis: {baseline: 0, viewWindow: {max:750}},
                    colors: ['#ff5a5f'],
                    height: height,
                    hAxis: hAxisOpts});

  // Weekly Posts
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Week');
  data.addColumn('number', 'Created_at');
  data.addColumn('number', 'Updated_at')
  data.addRows([
          {%- for k, v in weekly_posts_created_and_updated.items() %}
          [new Date({{ k.year }}, {{ k.month }}, {{ k.day }}), {{ v[0]}}, {{ v[1] }}],
          {%- endfor %}
  ]);
  data.sort(0);
  var chart = new google.visualization.LineChart(document.getElementById('posts_week'));
  chart.draw(data, {vAxis: {baseline: 0},
                    colors: ['#ff5a5f','#ffb400'],
                    height: height,
                    hAxis: hAxisOpts});

  // Weekly Posts Cumulative
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Week');
  data.addColumn('number', '# Posts')
  data.addRows([
          {%- for k, v in weekly_cumulative_posts.items() %}
          [new Date({{ k.year }}, {{ k.month }}, {{ k.day }}), {{ v }}],
          {%- endfor %}
  ]);
  data.sort(0);
  var chart = new google.visualization.LineChart(document.getElementById('posts_cum'));
  chart.draw(data, {vAxis: {baseline: 0},
                    colors: ['#ff5a5f'],
                    height: height,
                    hAxis: hAxisOpts});

  // Weekly PageViews
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Week');
  data.addColumn('number', 'Pageviews');
  data.addRows([
          {%- for k, v in weekly_pageviews.items() %}
          [new Date({{ k.year }}, {{ k.month }}, {{ k.day }}), {{ v }} ],
          {%- endfor %}
  ]);
  data.sort(0);
  var chart = new google.visualization.LineChart(document.getElementById('pageviews_weeks'));
  chart.draw(data, {vAxis: {baseline: 0},
                    colors: ['#007a87'],
                    height: height,
                    hAxis: hAxisOpts});

  // Number of posts per author
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'Author');
  data.addColumn('number', 'Number of posts');
  data.addRows([
          {%- for k, v in post_per_author_count.items() %}
          ["{{ k }}", {{ v }} ],
          {%- endfor %}
  ]);
  data.sort(0);
  var chart = new google.visualization.BarChart(document.getElementById('posts_per_author'));
  chart.draw(data, {hAxis: {baseline: 0, gridlines: {count: -1}},
                    colors: ['#007a87'],
                    height: height,
                    });

}

function search(s){
  window.location = '/feed?filters=' + $('#searchbar').val()
}

</script>

{% endblock %}

knowledge_repo/app/templates/traceback.html
<h1> Internal Server Error </h1>

<div>
    <pre>{{ info }}</pre>
</div>

knowledge_repo/app/templates/view_group_users.html
{% extends "base.html" %}

{% block title %} Knowledge {% endblock %}

{% block content %}
<div class="row col-12">
  <div class="panel">
    <div class="panel-header">
      Users associated with group: {{ group.name }}
    </div>
    <div class="panel-body">
      <ul style='list-style-type:none'>
        {% for user in group.users %}
        <li> {{ user.format_name }} -
            <a href="javascript:void(0)" onclick="delete_user({{user.id}});"> Delete User </a>
        </li>
        <br>
        {% endfor %}
      <ul>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
function delete_user(user_id){
  $.ajax({
      type: "POST",
      dataType: "json",
      data: JSON.stringify(user_id),
      contentType: "application/json",
      url: '/delete_user_from_group?group_id={{group.id}}',
      async: false,
    });
    location.reload();
}
</script>
{% endblock %}